# Vars

# Tests

# All
# go test -v -count=1 -timeout=5s  ./internal/repo/user_test.go
test-selected:
	clear
	make -f makefile.test test-auth-create-user
	@make spacer
	make -f makefile.test test-auth-get-users
	@make spacer
	make -f makefile.test test-auth-get-user
	@make spacer
	make -f makefile.test test-auth-update-user
	@make spacer
	make -f makefile.test test-auth-delete-user

# Auth
test-auth-create-user:
	go test -v -run TestCreateUser -count=1 -timeout=5s  ./pkg/auth/user_test.go

test-auth-get-users:
	go test -v -run TestGetUsers -count=1 -timeout=5s  ./pkg/auth/user_test.go

test-auth-get-user:
	go test -v -run TestGetUser -count=1 -timeout=5s  ./pkg/auth/user_test.go

test-auth-update-user:
	go test -v -run TestUpdateUser -count=1 -timeout=5s  ./pkg/auth/user_test.go

test-auth-delete-user:
	go test -v -run TestDeleteUser -count=1 -timeout=5s  ./pkg/auth/user_test.go

# Repo
test-repo-create-user:
	go test -v -run TestCreateUser -count=1 -timeout=5s  ./internal/repo/user_test.go

test-repo-get-users:
	go test -v -run TestGetAllUsers -count=1 -timeout=5s  ./internal/repo/user_test.go

test-repo-get-user-by-id:
	go test -v -run TestGetUserByID -count=1 -timeout=5s  ./internal/repo/user_test.go

test-repo-get-user-by-slug:
	go test -v -run TestGetUserBySlug -count=1 -timeout=5s  ./internal/repo/user_test.go

test-repo-get-user-by-username:
	go test -v -run TestGetUserByUsername -count=1 -timeout=5s  ./internal/repo/user_test.go

test-repo-update-user:
	go test -v -run TestUpdateUser -count=1 -timeout=5s  ./internal/repo/user_test.go

test-repo-delete-user:
	go test -v -run TestDeleteUser -count=1 -timeout=5s  ./internal/repo/user_test.go

